export default {
  REQUEST_TEMP_AND_HUM: 'REQUEST_TEMP_AND_HUM',
  RECEIVE_TEMP_AND_HUM: 'RECEIVE_TEMP_AND_HUM',
  REQUEST_SNAPSHOTS: 'REQUEST_SNAPSHOTS',
  RECEIVE_SNAPSHOTS: 'RECEIVE_SNAPSHOTS',
};
